### ISSUE TITLE
Not an issue just a question

### ISSUE THREAD

**Issue by 6R1M4C3** [yaroslaff/nudecrawler#4]
Hello, how come when I search a term on your application it returns 1 or 2 results, but then I use another search service that I found online it returns many more for the exact search term?

**Comment by yaroslaff** [comment]
Hello!
Thank you for question.
There are three things which can limit results from nudecrawler.

1. Nudecrawler search only by exact title match. If you search "Sasha Grey" it can find all (or not all, depending on other settings) pages with title "Sasha Grey". But it will not find page with title "My favorite actress" even if this page has tons of her photos and text about Sasha Grey. This is technical limitation, Telegra.ph has no index of all pages, so we cannot find page unless we try to find it by title.
On other hand, nudecrawler performs real crawling (not just searching in database), so it can find pages which was not indexe
3. Date range. By default nudecrawler tries pages for today (this date of any year) and 30 days ago. You can adjust this with `--days`. Set 365 to find all.
4. Other filtering options. Nudecrawler can skip page (not print it to log) if it's "not interesting" (e.g. has no pages at all, or not enough nude images, or images are too small). This is intentional, to speed-up search (save time and do not check page which looks not very interesting right from start), but this can be adjusted by options. You can add `-a` option to display all pages.

**Comment by 6R1M4C3** [comment]
I found this website and if you search terms in this it seems to be returning more results, I was just curious as to why is it doing something different than this tool. [Searcher](https://telegcrack.com/). 

> Date range. By default nudecrawler tries pages for today (this date of any year) and 30 days ago. You can adjust this with --days. Set 365 to find all.
Other filtering options. Nudecrawler can skip page (not print it to log) if it's "not interesting" (e.g. has no pages at all, or not enough nude images, or images are too small). This is intentional, to speed-up search (save time and do not check page which looks not very interesting right from start), but this can be adjusted by options. You can add -a option to display all pages.

this would make sense actually I wonder if its returning more dates and using the filters will return more.

**Comment by yaroslaff** [comment]
to get most results: `-a -d 365`

**Comment by yaroslaff** [comment]
closing issue :-)

**Comment by yaroslaff** [comment]
closing
